/**
 * 全局通用枚举
 */

export enum FormTypes { // 表单类型
  INPUT = 'COMMON_INPUT',
  NUMBER = 'COMMON_INPUT_NUMBER',
  DATE = 'COMMON_DATE',
  RANGE_DATE = 'COMMON_RANGE_DATE',
  SELECT = 'COMMON_SELECT',
  BUSINESS_SELECT='BUSINESS_SELECT'
};
